server:
  port: 11059
spring:
  application:
    name: service
  datasource:
    dynamic:
      druid:
        initial-size: 1
        max-active: 300
        min-idle: 1
        max-wait: 10000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 100
        validation-query: select 1 from dual
        validation-query-timeout: 30
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        keep-alive: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 60000
        filters: stat,wall,config  #,log4j
        proxy-filters:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    port: 6379
    password: # 如果未单独配置默认为空即可
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  profiles:
    active: "local"
    #active: prod
    # 资源信息
    messages:
      # 国际化资源文件路径
      basename: i18n/messages
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    # 文件上传
    servlet:
      multipart:
        max-file-size: 30MB
        max-request-size: 30MB
    # 服务模块
    devtools:
      restart:
        # 热部署开关
        enabled: true
mybatis-plus:
  typeAliasesPackage: com.ares.service.domain
  mapperLocations: classpath:mapper/*.xml
  configuration:
    # 驼峰命名转换
    mapUnderscoreToCamelCase: true

logging:
  config: classpath:logback/logback-local.xml

